#!/bin/bash

set -xeuo pipefail

RUTHLESS_PATH="$HOME/.local/lib/ruthless"
IMAGES_PATH="$RUTHLESS_PATH/images"
DEVICE_PATH="$RUTHLESS_PATH/device.img"

mkdir -p "$RUTHLESS_PATH"
mkdir -p "$IMAGES_PATH"

truncate -s10G "$DEVICE_PATH"
DEVICE=$(sudo losetup --show --find "$DEVICE_PATH")

mkfs -t btrfs -f "$DEVICE_PATH"

sudo mount -o user_subvol_rm_allowed "$DEVICE" "$IMAGES_PATH"
USER=$(whoami)
GROUP=$(id -gn)
sudo chown "$USER":"$GROUP" "$IMAGES_PATH"